### PR TITLE
Amy/139 update views realtime

### PR DESCRIPTION
**Pull request by ajin12**

### CODE REVIEW

**Comment by alexandrashaw10** [comment]
Can you add a gif of how this looks?

**Comment by ajin12** [comment]
update_realtime

**Comment by alexandrashaw10** [comment]
Is there a way to get the comments to show up without refreshing the details page? Just so its more clear the post went through. If not, thats okay though we can close other things

**Comment by chiped** [comment]
Since you know that the update when through in the on success listener, you can update the UI with the text from the edittext

**Comment by ajin12** [comment]
Sounds good. What would be a good way to do this? I was trying to get the recycler view to update with the new comment but haven't gotten it to work - am I on the right track or should I do it a different way?

**Comment by chiped** [comment]
You can add it to the list backing your comments recyclerview in broadcast details activity. I noticed you don't have a successlistener on the call to post the comment. You can add a successlistener and update the list and notify dataset changed in the listener

**Comment by ajin12** [comment]
Ok thanks! I will work on that now

**Pull request closed without merging**
